### ISSUE TITLE
Question about raw data availability

### ISSUE THREAD

**Issue by MaestSi** [bjtrost/TCAG-WGS-CNV-workflow#1]
Dear Dr. Trost,
I found your manuscript about "A comprehensive Workflow for RD based CNV identification from WGS data" very interesting. Since I found this GitHub page with all scripts for reproducing results, I would like to know if raw reads (or BAM files) for some of the samples sequenced in the context of this work are publicly available.
Thank you in advance.

**Comment by bjtrost** [comment]
Hi,

Thanks for your message! We are in the process of submitting the HuRef and NA12878 sequencing data to the NCBI SRA. We will let you know when this is complete. If you'd like access to the MSSNG data, you can apply for access here (you will need an autism-related research question):

https://research.mss.ng/assets/documents/mssng_access_application.pdf

Let me know if you have any other questions.

Cheers,

Brett

**Comment by bjtrost** [comment]
Hi,

Sorry, the data got uploaded awhile ago but I had forgotten about this thread. The data are in NCBI SRA under accession numbers SRR9046647 (NA12878) and SRR9046649 (HuRef).
