### ISSUE TITLE
Error in CNV_read_depth_checker.sh

### ISSUE THREAD

**Issue by ikeadeshina** [bjtrost/TCAG-WGS-CNV-workflow#10]
Hi Brett, 

I'm trying to run your **CNV_read_depth_checker.sh** script and came across the error below. It's calling on **get_normalized_depth.py**, which is calling on **CNVworkflowlib.py** at this point.

I'm having trouble resolving it because "parse_region" isn't part of the **CNVworkflowlib.py** script and I'm afraid the problem affects lines 22, 25-26, 28-29, and 31. Am I missing something?

`$ ./CNV_read_depth_checker.sh proband_sorted.bam chr9:72777841-72778868`
`Traceback (most recent call last):`
`  File "get_normalized_depth.py", line 21, in <module>`
  `  chr, start, end = CNVworkflowlib.parse_region(args.region.replace(",", ""))`
`AttributeError: 'module' object has no attribute 'parse_region'`

**Comment by bjtrost** [comment]
Hi,

I pushed a new version - please check if it works. Thanks!

**Comment by ikeadeshina** [comment]
Thank you. I did check and came across a different error.

` $./CNV_read_depth_checker.sh proband_sorted.bam chr9:72777841-72778868`
`$ ./CNV_read_depth_checker.sh proband_sorted.bam 9:72777841-72778868`

I believe the first coordinate format is correct but in either case I have this error: 

`Invalid chromomosome 9 entered. Please try again.`

**Comment by bjtrost** [comment]
Sorry for the slow reply - I was away from work the last few days. I think it should be fixed now - can you try it again and let me know if it works for you? Thanks!
