### ISSUE TITLE
add_features.py '-c' parameter not working (?)

### ISSUE THREAD

**Issue by MaestSi** [bjtrost/TCAG-WGS-CNV-workflow#2]
Dear bjtrost,
I tried out the CNV discovery pipeline on NA12878 data.
Since I noted that erds+/NA12878.erds+.txt file contains the same variants reported in erds/merged/ NA12878.erds.vcf.cluster.txt, I had a look at the code, and I noticed that in process_cnvs_erds+.sh there is command:
`$python_path "$erds_plus" -i $erds_dir/merged/$f".erds.vcf.cluster.txt" -a $cnvn_dir/merged/$f".calls.txt.cluster.txt" -o $merge_dir/$f.erds+.txt -s $f -c 0 -p reciprocal`
with -c parameter set to 0.
When trying to set it to 50, to reproduce the 50% reciprocal overlap reported in the article, I noticed that the produced output file was the same as when I set -c to 0.
Do you know if there is something that I am missing?
Thanks

**Comment by bjtrost** [comment]
Hi,

The "-c" option will not actually change the number of lines. The change is in the last few columns (compare side by side for details). If you want to use 50% reciprocal overlap, you can filter the table such that erds_fraction and cnvn_fraction are both >= 0.5. 

Cheers,

Brett

**Comment by MaestSi** [comment]
Ok, so I should not modify the -c parameter, right?
For example, I noticed that when I let -c parameter set to default 0 value, when doing cut -f2,3,4,5,20,21, among many others, I had this line in output file (with column 20 corresponding to erds_fraction and column 21 corresponding to cnvn_fraction):

> chr1    2652001 2702000 DUP     1.0     0.5319148936170213

While when setting -c to 50 and printing the same columns I had:

> chr1    2652001 2702000 DUP     0.96    1.0

Can you please explain me why, in output file obtained with '-c 50', I have that erds_fraction and cnvn_fraction report different numbers? I would have expected only a '-' when erds_fraction or cnvn_fraction were minor than the -c value.

As you said before, to reproduce the results reported in the article, I should let -c parameter to default 0 value, and filter only rows reporting both erds_fraction and cnvn_fraction > 50, but I was just curious to understand why can these numbers change.
Thanks

**Comment by bjtrost** [comment]
Hi,

Thanks for your question and sorry for the late reply! Note that the script is designed to handle fragmented CNV calls. The behavior is that if you set -c = 0, then any CNVnator CNVs that overlap an ERDS CNV contribute to erds_fraction. So if you have a single ERDS call that entirely overlaps three separate CNVnator calls, and in aggregate the CNVnator calls overlap with 90% of the ERDS CNV, then erds_fraction = 0.9 and cnvn_fraction = 1. However, if you set c = 50, then only CNVnator calls that overlap with 50% of the ERDS call are counted toward the total, which (in the prior example) would result in cnvn_fraction = - and erds_fraction = - (or could result in different numbers, as in the example you gave).

**Comment by MaestSi** [comment]
Hi,
so if I understood correctly, in the previous example I reported, we have that those particular sets of CNV calls at chr1: 2652001 by ERDS are more fragmented than those by CNVnator. In fact, when considering all possible CNV sizes for contribution to the meged CNV (c=0) we have that only 53% of ERDS merged calls are also called by CNVnator (ERDS fraction = 1; CNVnator fraction = 0.53); however, when I require that each CNV call is at least 50% of the whole set of CNVs by that software (c=50) I have that the most extended set of "surviving" CNVs is the one predicted by CNVnator (CNVnator fraction = 1), and it is almost completely covered (ERDS fraction = 0.96) by the set of "surviving" calls by ERDS.

Thanks and all the best.
