### ISSUE TITLE
merge_cnvnator_results.py not including appropriate chr names with hg38

### ISSUE THREAD

**Issue by MaestSi** [bjtrost/TCAG-WGS-CNV-workflow#3]
Dear bjtrost,
after changing the line:
`gap_file="$root"/hg19_gap.bed`
to
`gap_file="$root"/hg38_gap.bed`
in process_cnvs.erds+.sh (and saving the appropriate gap table), I noticed that the file cnvn/merged/NA12878.calls.txt.cluster.txt also contains some lines where the second column (the chromosome ID) is missing 'chr'.
I think this may be due to some commands in merge_cnvnator_results.py script (probably something like the following):
`chrm = words[1].replace("chr","")`
How do you think this could be solved?
Thank you

**Comment by bjtrost** [comment]
Hi,

This can be solved by removing the .replace("chr","") part. I updated the scripts on GitHub.

Cheers,

Brett

**Comment by MaestSi** [comment]
Ok, thank you!

**Comment by MaestSi** [comment]
Dear Brett,
I re-git cloned the repository, and noticed you restored the <.replace("chr","")> part in the files, as they were before your modification (the update you are writing about in your previous post in this thread). I guess they caused some problems with hg19 reference. So, I am going to remove the <.replace("chr","")> part again in downloaded files. However, I noticed you did another few modifications in add_features.py file. Can I let them as they are in the current version, or do I have to restore also those parts as they were prior to you modification?
Thanks.

**Comment by MaestSi** [comment]
Dear Brett,
I git cloned the "chr-fix" branch and removed 'chr' prefix from the hg38_gap.bed. Everything seems to work, I added the 'chr' prefix in the final bed file at the end of the analysis, so thank you!
Simone
