### ISSUE TITLE
What is the echo $f" "$g means in process_cnvs.erds+.sh

### ISSUE THREAD

**Issue by JieYang031** [bjtrost/TCAG-WGS-CNV-workflow#4]
I am trying to use the code provided with this workflow to merge the CNV results from CNVnator and ERDS. More specifically, using the process_cnvs.erds+.sh file. 
However, it comes with an error on line 81. I find the error comes from the echo $f" "$g. It seems like something missing then this cannot be interpreted correctly. I run one by one for line 81 as:

[jyang32@cnode337 filtered]$ echo for f in `ls $cnvn_dir/formatted_filtered/filtered/`
for f in TCGA-05-5429-01A-01D-1625-08.calls.filtered.txt
[jyang32@cnode337 filtered]$ echo do g=`echo $f| sed 's/.calls.filtered.txt//g'`
do g=TCGA-05-5429-01A-01D-1625-08
[jyang32@cnode337 filtered]$ echo $f"TCGA-05-5429-01A-01D-1625-08.calls.filtered.txt" "$g
> 
> 
Can you please let me know what is this used for? Maybe then I can figure out where is the problem.

**Comment by bjtrost** [comment]
Hi,

Check out the comments at the top of the script, which explain the naming conventions to use for the raw ERDS/CNVnator files (which go in the "original" directories). I think the problem is happening because your files are not named according to that convention. Let me know if fixing this corrects the problem. Thanks!

**Comment by JieYang031** [comment]
Hi, I have double checked the file and folder names. It is still not working. I think it is the code. Can you please check the line which generate the $alt_cnvn?

**Comment by bjtrost** [comment]
Hi, 

Sorry for the slow reply. We are looking into this now and will let you know when we have an answer. Thanks for your patience!

Cheers,

Brett

**Comment by JieYang031** [comment]
Hi Brett,

Thanks for the reply. I do not get any error message, but a wrong alt.cnvn.txt.
I used one TCGA samples for this program. I get following variable value for the cnvn command:
>>>echo $g
TCGA-05-5429-01A-01D-1625-08
>>>echo $f
TCGA-05-5429-01A-01D-1625-08.calls.filtered.txt. 
I am sure they are in the correct directory. Then after apply the following command: 
>>>for f in `ls $cnvn_dir/formatted_filtered/filtered/`; do g=`echo $f| sed 's/.calls.filtered.txt//g'`; echo $f"	"$g; done > $alt_cnvn
What I get for alt.cnvn.txt is just:
>>>cat alt.cnvn.txt
TCGA-05-5429-01A-01D-1625-08.calls.filtered.txtTCGA-05-5429-01A-01D-1625-08
With this alt.cnvn.txt, I cannot proceed to the next command.
That is why I want to know what exactly we did to generate the alt.cnvn.txt. I still cannot get the right file.

Thanks,
Jie

**Comment by bjtrost** [comment]
Hi,

Your alt.cnvn.txt file looks like I would expect, except that there should be whitespace between "TCGA-05-5429-01A-01D-1625-08.calls.filtered.txt" and "TCGA-05-5429-01A-01D-1625-08". But is the lack of space just an artifact of the GitHib formatting?

Can you include the full log for your command? It might be something else that is going wrong.

**Comment by JieYang031** [comment]
Hi,

I run the code one by one and find the reason why it failed when applying the merge_cnvnator_results.py and merge_erds_results.py. The chromosome information of CNV called by CNVnator and ERDS in my results are annotated by "1" or "2", while the hg19.bed file is annotated as "chr1" or "chr2". I changed the key used for the gap dictionary from gaps[c] to gaps["chr"+c] solved the problem. 
Then, I re-run the process_cnvs.erds+.sh, there is no problem of the merge functions, but one error come out with the add_features.py (shown as below):
>>>/Volumes/sulman_lab/Users_Current/JieYang/Currently_working_sep23_copy/MethyCNV/TCAG-WGS-CNV-workflow/format_cnvnator_results.py /Volumes/sulman_lab/Users_Current/JieYang/Currently_working_sep23_copy/MethyCNV/TCAG-WGS-CNV-workflow/format_erds_results.py /Volumes/sulman_lab/Users_Current/JieYang/Currently_working_sep23_copy/MethyCNV/TCAG-WGS-CNV-workflow/merge_cnvnator_results.py /Volumes/sulman_lab/Users_Current/JieYang/Currently_working_sep23_copy/MethyCNV/TCAG-WGS-CNV-workflow/merge_erds_results.py /Volumes/sulman_lab/Users_Current/JieYang/Currently_working_sep23_copy/MethyCNV/TCAG-WGS-CNV-workflow/add_features.py /Volumes/sulman_lab/Users_Current/JieYang/Currently_working_sep23_copy/MethyCNV/TCAG-WGS-CNV-workflow/hg19_gap.bed
Set-up..
Found erds/original, creating erds/fFound erds/original, creating erds/formatted
rm: /Volumes/sulman_lab/Users_Current/JieYang/Currently_working_sep23_copy/MethyCNV/Test/TCGA-05-5429-01A-01D-1625-08/temp/mycnvs//erds/merged/*: No such file or directory
Found cnvn/original, creating cnvn/formatted_filtered
rm: /Volumes/sulman_lab/Users_Current/JieYang/Currently_working_sep23_copy/MethyCNV/Test/TCGA-05-5429-01A-01D-1625-08/temp/mycnvs//cnvn/merged/*: No such file or directory
Found erds+, deleting files
Formatting, filtering and merging cnvn output
Warning: Header not found, using default..
Formatting and merging erds output
genearting sample ids..
merging erds and cnvn calls
Traceback (most recent call last):
  File "/Volumes/sulman_lab/Users_Current/JieYang/Currently_working_sep23_copy/MethyCNV/TCAG-WGS-CNV-workflow/add_features.py", line 288, in <module>
    temp_str += "\t"+`calls[sample][id][0]`+"\t"+calls[sample][id][1]+"\t"+calls[sample][id][2]+"\t"+calls[sample][id][3]+"\t"+calls[sample][id][4] + "\t-\t-"
IndexError: list index out of range
check log files..

**Comment by bjtrost** [comment]
Hi,

Can you send me the ERDS and CNVnator output files you are using? This would be easier if I can test it myself using your exact files. Thanks! brett.trost@sickkids.ca

**Comment by bjtrost** [comment]
Hi,

I pushed a new update to the repository. It should fix both the issues. Let me know!

**Comment by JieYang031** [comment]
Hi, the updated code works and generate more calls than my previous calls. 
The generated erds+.txt file is almost the same as the erds.vcf.cluster.txt for CNV calls.

**Comment by JieYang031** [comment]
So, in this step, we are merging the information from both ERDS and CNVnator, right? If we want to obtain the final CNV call set, we will need to further filter based on the reds+.txt file?
I want to know which step is this shell file processed compared to the Figure 3 in the manuscript? Is it "Use CNVnator ERDS intersection" for deletion, and "Use CNVnator-ERDS intersection as high-confidence set and ERDS only as discovery set"? Or have already goes to the next yellow diamond "CNVs of paritcular importance/interest"?

**Comment by bjtrost** [comment]
The high-confidence set is the CNVs having 50% reciprocal overlap between ERDS and CNVnator (erds_fraction column >= 0.5 and cnvn_fraction column >= 0.5). For duplications, we found that ERDS-only calls are somewhat reliable (especially for small CNVs, 1000-5000 bp, for which CNVnator makes few or no calls), so you can use those too if you want to increase sensitivity.
