### ISSUE TITLE
Empty VCF result for ERDS_TCAG run

### ISSUE THREAD

**Issue by ikeadeshina** [bjtrost/TCAG-WGS-CNV-workflow#8]
Hi, 

While running erds_tcag, I find that the run seems successfully but the resulting VCF is empty. Below are the details of the run. What could be causing this problem? I would appreciate anyway you can be of help @bjtrost . 

`############################ERDS1.1############################
Your input command line is
perl /mnt/data/ike/software/ERDS-master/erds_tcag/src/erds_pipeline.pl -b Data_Files/BAM_old/sample1_sorted.bam -v Data_Files/VCF/sample1.vcf -o ERDS_TCAG_indVCF_sample1 -r /mnt/data/reference/hs37d5.fa 
13:39:55 Jan 8 2020	ERDS stared step 0 in sample1...
[Wed Jan  8 13:39:55 2020] PID 20759 is performing computation for hs37d5
[Wed Jan  8 13:39:55 2020] PID 20760 is performing computation for NC_007605
[Wed Jan  8 13:39:55 2020] PID 20761 is performing computation for GL000192.1
[Wed Jan  8 13:39:55 2020] PID 20762 is performing computation for GL000225.1
[Wed Jan  8 13:39:56 2020] PID 20760 is performing computation for GL000193.1
[Wed Jan  8 13:39:56 2020] PID 20759 is performing computation for GL000194.1
[Wed Jan  8 13:39:56 2020] PID 20762 is performing computation for GL000222.1
[Wed Jan  8 13:39:56 2020] PID 20761 is performing computation for GL000200.1
[Wed Jan  8 13:39:57 2020] PID 20760 is performing computation for GL000195.1
[Wed Jan  8 13:39:57 2020] PID 20759 is performing computation for GL000212.1
[Wed Jan  8 13:39:57 2020] PID 20762 is performing computation for GL000224.1
[Wed Jan  8 13:39:57 2020] PID 20761 is performing computation for GL000223.1
[Wed Jan  8 13:39:58 2020] PID 20760 is performing computation for GL000205.1
[Wed Jan  8 13:39:58 2020] PID 20759 is performing computation for GL000219.1
[Wed Jan  8 13:39:58 2020] PID 20762 is performing computation for GL000216.1
[Wed Jan  8 13:39:58 2020] PID 20761 is performing computation for GL000215.1
[Wed Jan  8 13:40:02 2020] PID 20760 is performing computation for GL000199.1
[Wed Jan  8 13:40:02 2020] PID 20759 is performing computation for GL000217.1
[Wed Jan  8 13:40:02 2020] PID 20761 is performing computation for GL000211.1
[Wed Jan  8 13:40:02 2020] PID 20762 is performing computation for GL000213.1
[Wed Jan  8 13:40:02 2020] PID 20760 is performing computation for GL000218.1
[Wed Jan  8 13:40:02 2020] PID 20759 is performing computation for GL000220.1
[Wed Jan  8 13:40:02 2020] PID 20761 is performing computation for GL000209.1
[Wed Jan  8 13:40:03 2020] PID 20762 is performing computation for GL000221.1
[Wed Jan  8 13:40:03 2020] PID 20759 is performing computation for GL000214.1
[Wed Jan  8 13:40:03 2020] PID 20760 is performing computation for GL000228.1
[Wed Jan  8 13:40:03 2020] PID 20761 is performing computation for GL000227.1
[Wed Jan  8 13:40:04 2020] PID 20762 is performing computation for GL000191.1
[Wed Jan  8 13:40:04 2020] PID 20759 is performing computation for GL000208.1
[Wed Jan  8 13:40:04 2020] PID 20760 is performing computation for GL000198.1
[Wed Jan  8 13:40:04 2020] PID 20761 is performing computation for GL000204.1
[Wed Jan  8 13:40:05 2020] PID 20762 is performing computation for GL000233.1
[Wed Jan  8 13:40:05 2020] PID 20759 is performing computation for GL000237.1
[Wed Jan  8 13:40:05 2020] PID 20760 is performing computation for GL000230.1
[Wed Jan  8 13:40:05 2020] PID 20761 is performing computation for GL000242.1
[Wed Jan  8 13:40:10 2020] PID 20762 is performing computation for GL000243.1
[Wed Jan  8 13:40:11 2020] PID 20759 is performing computation for GL000241.1
[Wed Jan  8 13:40:15 2020] PID 20760 is performing computation for GL000236.1
[Wed Jan  8 13:40:15 2020] PID 20761 is performing computation for GL000240.1
[Wed Jan  8 13:40:17 2020] PID 20762 is performing computation for GL000206.1
[Wed Jan  8 13:40:17 2020] PID 20759 is performing computation for GL000232.1
[Wed Jan  8 13:40:17 2020] PID 20760 is performing computation for GL000234.1
[Wed Jan  8 13:40:17 2020] PID 20761 is performing computation for GL000202.1
[Wed Jan  8 13:40:18 2020] PID 20762 is performing computation for GL000238.1
[Wed Jan  8 13:40:18 2020] PID 20759 is performing computation for GL000244.1
[Wed Jan  8 13:40:18 2020] PID 20760 is performing computation for GL000248.1
[Wed Jan  8 13:40:18 2020] PID 20761 is performing computation for GL000196.1
[Wed Jan  8 13:40:18 2020] PID 20762 is performing computation for GL000249.1
[Wed Jan  8 13:40:18 2020] PID 20759 is performing computation for GL000246.1
[Wed Jan  8 13:40:18 2020] PID 20760 is performing computation for GL000203.1
[Wed Jan  8 13:40:19 2020] PID 20761 is performing computation for GL000197.1
[Wed Jan  8 13:40:19 2020] PID 20762 is performing computation for GL000245.1
[Wed Jan  8 13:40:19 2020] PID 20759 is performing computation for GL000247.1
[Wed Jan  8 13:40:19 2020] PID 20760 is performing computation for GL000201.1
[Wed Jan  8 13:40:19 2020] PID 20761 is performing computation for GL000235.1
[Wed Jan  8 13:40:19 2020] PID 20762 is performing computation for GL000239.1
[Wed Jan  8 13:40:20 2020] PID 20759 is performing computation for GL000210.1
[Wed Jan  8 13:40:21 2020] PID 20760 is performing computation for GL000231.1
[Wed Jan  8 13:40:25 2020] PID 20761 is performing computation for GL000229.1
[Wed Jan  8 13:40:25 2020] PID 20762 is performing computation for GL000226.1
[Wed Jan  8 13:40:28 2020] PID 20759 is performing computation for GL000207.1
[Wed Jan  8 13:40:29 2020] PID 20760 is performing computation for MT
[Wed Jan  8 13:40:29 2020] PID 20761 is performing computation for Y
[Wed Jan  8 13:40:29 2020] PID 20762 is performing computation for X
[Wed Jan  8 13:40:30 2020] PID 20759 is performing computation for 22
[Wed Jan  8 13:40:30 2020] PID 20761 is performing computation for 20
[Wed Jan  8 13:40:31 2020] PID 20762 is performing computation for 19
[Wed Jan  8 13:40:31 2020] PID 20759 is performing computation for 18
[Wed Jan  8 13:40:35 2020] PID 20761 is performing computation for 16
[Wed Jan  8 13:40:35 2020] PID 20762 is performing computation for 15
[Wed Jan  8 13:40:35 2020] PID 20759 is performing computation for 14
[Wed Jan  8 13:40:36 2020] PID 20761 is performing computation for 12
[Wed Jan  8 13:40:36 2020] PID 20762 is performing computation for 11
[Wed Jan  8 13:40:36 2020] PID 20759 is performing computation for 10
[Wed Jan  8 13:40:36 2020] PID 20761 is performing computation for 8
[Wed Jan  8 13:40:36 2020] PID 20762 is performing computation for 7
[Wed Jan  8 13:40:37 2020] PID 20759 is performing computation for 6
[Wed Jan  8 13:40:37 2020] PID 20761 is performing computation for 4
[Wed Jan  8 13:40:37 2020] PID 20762 is performing computation for 3
[Wed Jan  8 13:40:37 2020] PID 20759 is performing computation for 2
[Wed Jan  8 13:40:39 2020] PID 20760 is performing computation for 21
[Wed Jan  8 13:40:45 2020] PID 20760 is performing computation for 17
[Wed Jan  8 13:40:45 2020] PID 20760 is performing computation for 13
[Wed Jan  8 13:40:46 2020] PID 20760 is performing computation for 9
[Wed Jan  8 13:40:46 2020] PID 20760 is performing computation for 5
[Wed Jan  8 13:40:47 2020] PID 20760 is performing computation for 1
13:40:48 Jan 8 2020	ERDS finished step 0 in sample1...
13:40:48 Jan 8 2020	ERDS stared step 1 in sample1...
13:41:11 Jan 8 2020	ERDS finished step 1 in sample1...
13:41:11 Jan 8 2020	ERDS stared step 2 in sample1...
no chromosome ERDS_TCAG_indVCF_sample1/cnv/1.rd
Can't open ERDS_TCAG_indVCF_sample1/cnv/1.vit at ERDS_TCAG_indVCF_sample1/script/em.pl line 95.
13:41:12 Jan 8 2020	ERDS finished step 2 in sample1...
13:41:12 Jan 8 2020	ERDS stared step 3 in sample1...
[Wed Jan  8 13:41:12 2020] PID 21882 is performing computation for Y
[Wed Jan  8 13:41:12 2020] PID 21883 is performing computation for X
[Wed Jan  8 13:41:12 2020] PID 21884 is performing computation for 22
[Wed Jan  8 13:41:12 2020] PID 21885 is performing computation for 21
no chromosome ERDS_TCAG_indVCF_sample1/cnv/X.rd
no chromosome ERDS_TCAG_indVCF_sample1/cnv/21.rd
[Wed Jan  8 13:41:12 2020] PID 21883 is performing computation for 19
[Wed Jan  8 13:41:12 2020] PID 21885 is performing computation for 17
no chromosome ERDS_TCAG_indVCF_sample1/cnv/22.rd
[Wed Jan  8 13:41:12 2020] PID 21882 is performing computation for 20
[Wed Jan  8 13:41:12 2020] PID 21884 is performing computation for 18
no chromosome ERDS_TCAG_indVCF_sample1/cnv/19.rd
no chromosome ERDS_TCAG_indVCF_sample1/cnv/17.rd
[Wed Jan  8 13:41:12 2020] PID 21883 is performing computation for 15
[Wed Jan  8 13:41:12 2020] PID 21885 is performing computation for 13
no chromosome ERDS_TCAG_indVCF_sample1/cnv/20.rd
no chromosome ERDS_TCAG_indVCF_sample1/cnv/18.rd
[Wed Jan  8 13:41:12 2020] PID 21882 is performing computation for 16
[Wed Jan  8 13:41:12 2020] PID 21884 is performing computation for 14
no chromosome ERDS_TCAG_indVCF_sample1/cnv/13.rd
[Wed Jan  8 13:41:12 2020] PID 21885 is performing computation for 9
no chromosome ERDS_TCAG_indVCF_sample1/cnv/15.rd
no chromosome ERDS_TCAG_indVCF_sample1/cnv/14.rd
[Wed Jan  8 13:41:12 2020] PID 21883 is performing computation for 11
no chromosome ERDS_TCAG_indVCF_sample1/cnv/16.rd
[Wed Jan  8 13:41:12 2020] PID 21884 is performing computation for 10
[Wed Jan  8 13:41:12 2020] PID 21882 is performing computation for 12
no chromosome ERDS_TCAG_indVCF_sample1/cnv/9.rd
no chromosome ERDS_TCAG_indVCF_sample1/cnv/10.rd
no chromosome ERDS_TCAG_indVCF_sample1/cnv/11.rd
no chromosome ERDS_TCAG_indVCF_sample1/cnv/12.rd
[Wed Jan  8 13:41:12 2020] PID 21884 is performing computation for 6
[Wed Jan  8 13:41:12 2020] PID 21883 is performing computation for 7
[Wed Jan  8 13:41:12 2020] PID 21885 is performing computation for 5
[Wed Jan  8 13:41:12 2020] PID 21882 is performing computation for 8
no chromosome ERDS_TCAG_indVCF_sample1/cnv/7.rd
no chromosome ERDS_TCAG_indVCF_sample1/cnv/5.rd
[Wed Jan  8 13:41:12 2020] PID 21883 is performing computation for 3
[Wed Jan  8 13:41:12 2020] PID 21885 is performing computation for 1
no chromosome ERDS_TCAG_indVCF_sample1/cnv/8.rd
no chromosome ERDS_TCAG_indVCF_sample1/cnv/6.rd
[Wed Jan  8 13:41:12 2020] PID 21882 is performing computation for 4
[Wed Jan  8 13:41:12 2020] PID 21884 is performing computation for 2
no chromosome ERDS_TCAG_indVCF_sample1/cnv/1.rd
no chromosome ERDS_TCAG_indVCF_sample1/cnv/3.rd
no chromosome ERDS_TCAG_indVCF_sample1/cnv/2.rd
no chromosome ERDS_TCAG_indVCF_sample1/cnv/4.rd
13:41:12 Jan 8 2020	ERDS finished step 3 in sample1...
13:41:12 Jan 8 2020	ERDS stared step 4 in sample1...
[Wed Jan  8 13:41:12 2020] PID 21911 is performing computation for Y
[Wed Jan  8 13:41:12 2020] PID 21912 is performing computation for X
[Wed Jan  8 13:41:12 2020] PID 21913 is performing computation for 22
[Wed Jan  8 13:41:12 2020] PID 21914 is performing computation for 21
no chromosome ERDS_TCAG_indVCF_sample1/cnv/21.vit
[Wed Jan  8 13:41:12 2020] PID 21914 is performing computation for 17
no chromosome ERDS_TCAG_indVCF_sample1/cnv/22.vit
[Wed Jan  8 13:41:12 2020] PID 21913 is performing computation for 18
[Wed Jan  8 13:41:12 2020] PID 21911 is performing computation for 20
no chromosome ERDS_TCAG_indVCF_sample1/cnv/X.vit
[Wed Jan  8 13:41:12 2020] PID 21912 is performing computation for 19
no chromosome ERDS_TCAG_indVCF_sample1/cnv/17.vit
[Wed Jan  8 13:41:12 2020] PID 21914 is performing computation for 13
no chromosome ERDS_TCAG_indVCF_sample1/cnv/18.vit
no chromosome ERDS_TCAG_indVCF_sample1/cnv/19.vit
[Wed Jan  8 13:41:12 2020] PID 21913 is performing computation for 14
no chromosome ERDS_TCAG_indVCF_sample1/cnv/20.vit
[Wed Jan  8 13:41:12 2020] PID 21912 is performing computation for 15
[Wed Jan  8 13:41:12 2020] PID 21911 is performing computation for 16
no chromosome ERDS_TCAG_indVCF_sample1/cnv/13.vit
[Wed Jan  8 13:41:12 2020] PID 21914 is performing computation for 9
no chromosome ERDS_TCAG_indVCF_sample1/cnv/14.vit
[Wed Jan  8 13:41:12 2020] PID 21913 is performing computation for 10
no chromosome ERDS_TCAG_indVCF_sample1/cnv/16.vit
no chromosome ERDS_TCAG_indVCF_sample1/cnv/15.vit
[Wed Jan  8 13:41:12 2020] PID 21911 is performing computation for 12
[Wed Jan  8 13:41:12 2020] PID 21912 is performing computation for 11
no chromosome ERDS_TCAG_indVCF_sample1/cnv/9.vit
[Wed Jan  8 13:41:12 2020] PID 21914 is performing computation for 5
no chromosome ERDS_TCAG_indVCF_sample1/cnv/10.vit
no chromosome ERDS_TCAG_indVCF_sample1/cnv/12.vit
[Wed Jan  8 13:41:12 2020] PID 21913 is performing computation for 6
no chromosome ERDS_TCAG_indVCF_sample1/cnv/11.vit
[Wed Jan  8 13:41:12 2020] PID 21911 is performing computation for 8
[Wed Jan  8 13:41:12 2020] PID 21912 is performing computation for 7
no chromosome ERDS_TCAG_indVCF_sample1/cnv/5.vit
[Wed Jan  8 13:41:12 2020] PID 21914 is performing computation for 1
no chromosome ERDS_TCAG_indVCF_sample1/cnv/6.vit
no chromosome ERDS_TCAG_indVCF_sample1/cnv/8.vit
no chromosome ERDS_TCAG_indVCF_sample1/cnv/7.vit
[Wed Jan  8 13:41:12 2020] PID 21913 is performing computation for 2
[Wed Jan  8 13:41:12 2020] PID 21911 is performing computation for 4
[Wed Jan  8 13:41:12 2020] PID 21912 is performing computation for 3
no chromosome ERDS_TCAG_indVCF_sample1/cnv/1.vit
no chromosome ERDS_TCAG_indVCF_sample1/cnv/2.vit
no chromosome ERDS_TCAG_indVCF_sample1/cnv/4.vit
no chromosome ERDS_TCAG_indVCF_sample1/cnv/3.vit
13:41:12 Jan 8 2020	ERDS finished step 4 in sample1...
13:41:12 Jan 8 2020	ERDS stared step 5 in sample1...
13:41:12 Jan 8 2020	ERDS finished step 5 in sample1...
13:41:12 Jan 8 2020	ERDS stared step 6 in sample1...
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/1.rd
Can't open ERDS_TCAG_indVCF_sample1/cnv_1000/1.vit at ERDS_TCAG_indVCF_sample1/script/pre_hmm_dup.pl line 206.
13:41:36 Jan 8 2020	ERDS finished step 6 in sample1...
13:41:36 Jan 8 2020	ERDS stared step 7 in sample1...
[Wed Jan  8 13:41:36 2020] PID 21975 is performing computation for Y
[Wed Jan  8 13:41:36 2020] PID 21976 is performing computation for X
[Wed Jan  8 13:41:36 2020] PID 21977 is performing computation for 22
[Wed Jan  8 13:41:36 2020] PID 21978 is performing computation for 21
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/22.rd
[Wed Jan  8 13:41:36 2020] PID 21977 is performing computation for 18
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/21.rd
[Wed Jan  8 13:41:36 2020] PID 21975 is performing computation for 20
[Wed Jan  8 13:41:36 2020] PID 21978 is performing computation for 17
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/X.rd
[Wed Jan  8 13:41:36 2020] PID 21976 is performing computation for 19
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/18.rd
[Wed Jan  8 13:41:36 2020] PID 21977 is performing computation for 14
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/20.rd
[Wed Jan  8 13:41:36 2020] PID 21975 is performing computation for 16
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/17.rd
[Wed Jan  8 13:41:36 2020] PID 21978 is performing computation for 13
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/19.rd
[Wed Jan  8 13:41:36 2020] PID 21976 is performing computation for 15
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/14.rd
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/16.rd
[Wed Jan  8 13:41:36 2020] PID 21977 is performing computation for 10
[Wed Jan  8 13:41:36 2020] PID 21975 is performing computation for 12
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/13.rd
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/15.rd
[Wed Jan  8 13:41:36 2020] PID 21978 is performing computation for 9
[Wed Jan  8 13:41:36 2020] PID 21976 is performing computation for 11
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/12.rd
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/9.rd
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/11.rd
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/10.rd
[Wed Jan  8 13:41:36 2020] PID 21978 is performing computation for 5
[Wed Jan  8 13:41:36 2020] PID 21975 is performing computation for 8
[Wed Jan  8 13:41:36 2020] PID 21976 is performing computation for 7
[Wed Jan  8 13:41:36 2020] PID 21977 is performing computation for 6
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/5.rd
[Wed Jan  8 13:41:36 2020] PID 21978 is performing computation for 1
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/7.rd
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/6.rd
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/8.rd
[Wed Jan  8 13:41:36 2020] PID 21976 is performing computation for 3
[Wed Jan  8 13:41:36 2020] PID 21977 is performing computation for 2
[Wed Jan  8 13:41:36 2020] PID 21975 is performing computation for 4
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/2.rd
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/1.rd
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/4.rd
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/3.rd
13:41:36 Jan 8 2020	ERDS finished step 7 in sample1...
13:41:36 Jan 8 2020	ERDS stared step 8 in sample1...
[Wed Jan  8 13:41:36 2020] PID 22004 is performing computation for Y
[Wed Jan  8 13:41:36 2020] PID 22005 is performing computation for X
[Wed Jan  8 13:41:36 2020] PID 22006 is performing computation for 22
[Wed Jan  8 13:41:36 2020] PID 22007 is performing computation for 21
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/21.vit
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/22.vit
[Wed Jan  8 13:41:36 2020] PID 22007 is performing computation for 17
[Wed Jan  8 13:41:36 2020] PID 22006 is performing computation for 18
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/X.vit
[Wed Jan  8 13:41:36 2020] PID 22004 is performing computation for 20
[Wed Jan  8 13:41:36 2020] PID 22005 is performing computation for 19
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/18.vit
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/17.vit
[Wed Jan  8 13:41:36 2020] PID 22006 is performing computation for 14
[Wed Jan  8 13:41:36 2020] PID 22007 is performing computation for 13
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/19.vit
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/20.vit
[Wed Jan  8 13:41:36 2020] PID 22005 is performing computation for 15
[Wed Jan  8 13:41:36 2020] PID 22004 is performing computation for 16
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/13.vit
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/14.vit
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/15.vit
[Wed Jan  8 13:41:36 2020] PID 22006 is performing computation for 10
[Wed Jan  8 13:41:36 2020] PID 22007 is performing computation for 9
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/16.vit
[Wed Jan  8 13:41:36 2020] PID 22005 is performing computation for 11
[Wed Jan  8 13:41:36 2020] PID 22004 is performing computation for 12
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/10.vit
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/9.vit
[Wed Jan  8 13:41:36 2020] PID 22006 is performing computation for 6
[Wed Jan  8 13:41:36 2020] PID 22007 is performing computation for 5
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/11.vit
[Wed Jan  8 13:41:36 2020] PID 22005 is performing computation for 7
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/12.vit
[Wed Jan  8 13:41:36 2020] PID 22004 is performing computation for 8
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/7.vit
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/5.vit
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/6.vit
[Wed Jan  8 13:41:36 2020] PID 22005 is performing computation for 3
[Wed Jan  8 13:41:36 2020] PID 22007 is performing computation for 1
[Wed Jan  8 13:41:36 2020] PID 22006 is performing computation for 2
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/8.vit
[Wed Jan  8 13:41:36 2020] PID 22004 is performing computation for 4
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/3.vit
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/1.vit
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/2.vit
no chromosome ERDS_TCAG_indVCF_sample1/cnv_1000/4.vit
13:41:36 Jan 8 2020	ERDS finished step 8 in sample1...
13:41:36 Jan 8 2020	ERDS stared step 9 in sample1...
13:41:36 Jan 8 2020	ERDS finished step 9 in sample1...
13:41:36 Jan 8 2020	ERDS stared step 10 in sample1...
13:41:36 Jan 8 2020	ERDS finished all steps in sample1. The results are at ERDS_TCAG_indVCF_sample1.

############################ERDS1.1############################

`

**Comment by bjtrost** [comment]
Hi @ikeadeshina,

There are some error messages in the log - the first one being "no chromosome ERDS_TCAG_indVCF_sample1/cnv/1.rd". This likely means that something went wrong at an earlier step. Also, the log indicates that step 0 finished in less than a minute, which is way too fast. How long ago did you download TCAG ERDS? There was a fix pushed about 6 months ago that fixed an issue where, depending on system settings, the program could run out of memory, and could potentially explain the error you are getting. If not, was there any other error messages/logging produced that might help diagnose the problem?

Cheers,

Brett

**Comment by ikeadeshina** [comment]
Hi @bjtrost , 

I agree that something went wrong because the entire run "completed in 2 minutes. I downloaded TCAG ERDS yesterday from https://github.com/igm-team/ERDS. 

I copied (above) all that was printed to standard output. Looking in the directories created from the run, it looks like the `log` directory is empty. Is there somewhere in particular I should be looking?

I did the same exact run using the original script `ERDS-master/erds1.1/erds_pipeline.pl` and that was successful. But it took 14 hours for one genome at 30X.

**Comment by bjtrost** [comment]
Can you try running the read_bam program on its own (with no arguments) and let me know what you get? I get the following:

$ ./read_bam
Input error: incorrect number of command-line arguments.
Usage: ./read_bam bam_file ins_pem min_det_size chr aligned_length_thh CIGAR_length large_pem win_size_del read_length output_file

**Comment by ikeadeshina** [comment]
Running in `ERDS-master/erds_tcag/src/`...
 
`$ ./read_bam`
Input error: incorrect number of command-line arguments.
Usage: ./read_bam bam_file ins_pem min_det_size chr aligned_length_thh CIGAR_length large_pem win_size_del read_length output_file

**Comment by bjtrost** [comment]
Is a "debug" folder created? Is there anything in there?

**Comment by ikeadeshina** [comment]
Yes it was. There are 343 files in the folder, ending with either ".err" or ".txt". Here are examples of the 4 types of files in the folder and their entries: 

read_bam_chr17.txt
`### PARAMETERS ###
bam_file: Data_Files/BAM_old/sample1_sorted.bam
ins_pem: 376
min_det_size: 378
chr: 17
aligned_length_thh: 30
CIGAR_length: 12
large_pem: 50000
win_size_del: 200
read_length: 151
chr_rc: ERDS_TCAG_indVCF_sample1/rc/17.rc
chr_sd_rc: ERDS_TCAG_indVCF_sample1/rc/17.sd.rc
output_file: ERDS_TCAG_indVCF_sample1/rc/17.pem.sam
samtools command is [samtools view -F 2048 'Data_Files/BAM_old/sample1_sorted.bam' 17]
change_name_1.txt (END) 
`

read_bam_chr17.err
`sh: samtools: command not found`

rd_bam_chr17.txt
`[Wed Jan  8 13:40:45 2020] Starting /mnt/data/ike/software/ERDS-master/erds_tcag/src/read_bam script with parameters 'Data_Files/BAM_old/sample1_sorted.bam' 376 378 '17' 30 12 50000 200 151 'ERDS_TCAG_indVCF_sample1/rc/17.rc' 'ERDS_TCAG_indVCF_sample1/rc/17.sd.rc' 'ERDS_TCAG_indVCF_sample1/rc/17.pem.sam'
read_bam script complete for chr17`

rd_bam_chr17.err
`[samopen] SAM header is present: 86 sequences.
[sam_read1] reference 'ID:SAMBLASTER    CL:samblaster -i stdin -o stdout --addMateTags -d /dev/fd/62 -s /dev/fd/63 --maxSplitCount 2 --maxUnmappedBases 50 --minIndelSize 50 --minNonOverlap 20 VN:0.1.22
is3/Data_Files/Processed_Fastq/sample1_PLsample11_MG01HX03_H3KWLCCXX_3_R1.fastq.gz /mnt/data/don/Project_NBU/Analysis3/Data_Files/Processed_Fastq/sample1_PLsample11_MG01HX03_H3KWLCCXX_3_R2.fastq.gz VN:0.7.9a-r788-dirty
' is recognized as '*'.
[main_samview] truncated file.
`

**Comment by bjtrost** [comment]
`sh: samtools: command not found`

This may explain it. Try making sure samtools is in your PATH and trying again. I should add this to the documentation.

**Comment by ikeadeshina** [comment]
That worked!! Thank you very much!! The `Sample1.erds.vcf` result file is not empty and looks complete. 

It took 2hrs 40 mins. Is this a reasonable run time? How can I make use of the `--cluster` option to make it go faster? It isn't very clear from the README. My cluster uses the slurm job scheduling system. `--cluster "sbatch -N 1 -n 1 -c 16 --error Logs/erds_%j.log --output Logs/erds_%j.out"` would make sense. But it doesn't work in this case.

**Comment by bjtrost** [comment]
Great! 2 hours and 40 minutes does seem reasonable. I have never used the --cluster option - this was in the original version of ERDS, but I was never able to get it working properly.  However, new to the TCAG ERDS is the -z option, which lets you specify the number of processors/threads to use. The default is 4.  You could try setting -z 8 or -z 16 (and also request the same number of processors when submitting the job to your cluster), and it should speed it up somewhat. You might have to request more memory as well. I'm not sure increasing the number of processors beyond 4 will speed it up *that* much, since some steps cannot be parallelized, but it should make some difference.

**Comment by ikeadeshina** [comment]
Got it. I'll try the -z option then. 

You mention adding to the documentation the need to add Samtools to our PATH. Where can I find this documentation? I'm assuming it also has the -z option. I don't see the updated options when I run `$ perl erds_pipeline.pl` in the src folder.

**Comment by bjtrost** [comment]
> Got it. I'll try the -z option then.
> 
> You mention adding to the documentation the need to add Samtools to our PATH. Where can I find this documentation? 

Sorry, I used the word "documentation" loosely - there isn't really any "extra" documentation for the TCAG version of ERDS. I will add this information about samtools needing to be in the PATH to the README on GitHub.

>I'm assuming it also has the -z option. I don't see the updated options when I run `$ perl erds_pipeline.pl` in the src folder.

Thanks for noticing this! I will push a new version of the code to GitHub that adds usage information for the new options.

**Comment by ikeadeshina** [comment]
Perfect!! One more pressing question for you: Have you tried using a multi-sample VCF as the input VCF for a single-sample run or must it be a single-sample VCF?

**Comment by bjtrost** [comment]
This question has occurred to us as well, but unfortunately we've never tested to see if a multi-sample VCF will work - sorry! If you do test it, please let me know what you find.

Cheers,

Brett

**Comment by ikeadeshina** [comment]
Gotcha. I'll be sure to let you know if I do. 

Thanks for everything! 
Ike
