### ISSUE TITLE
De Novo CNVs

### ISSUE THREAD

**Issue by ikeadeshina** [bjtrost/TCAG-WGS-CNV-workflow#9]
Hi Brett, 

In your paper you mention that you identified 71 genic CNVs in 959 MSSNG probands. I'm wondering if you performed any filtering steps to derive this number beyond intersecting de novo CNVs with a bed file of genic regions.

**Comment by bjtrost** [comment]
Hi,

Yes, that is essentially what we did.

Cheers,

Brett

**Comment by ikeadeshina** [comment]
Okay then. Could you help me diagnose how I could have 168 de novo genic CNVs for just one proband using the code below? I modeled this code after the text in your paper:

 "We identified genic CNVs that were detected by both CNVnator and ERDS in a given ASD-affected proband but neither algorithm in both parents. This was done for the 959 ASD-affected case subjects in the MSSNG dataset for which the proband and both parental samples were sequenced on HiSeq X (total corresponding parental samples = 1,523). Of 71 such CNVs, 50 were confirmed as de novo after BAM confirmation and experimental validation. Of the 21 that were not de novo, five were due to false positives in the proband and 16 were parental false negatives (File S8). Our detection rate for genic de novo CNVs (approximately one per 19 children with ASD) was similar to that of previous studies from our group and others, several of which used much more complex and labor-intensive sets of algorithms and methods than suggested here."

`$ bedtools intersect -f 0.5 -a proband.erds+.txt -b mother.erds.vcf.cluster.txt father.erds.vcf.cluster.txt father.calls.txt.cluster.txt mother.calls.txt.cluster.txt -v -header | bedtools window -w 3000 -a stdin -b sorted_refgene_b37_cds_3.bed -header -u`

proband.erds+.txt = CNVs detected by both CNVnator and ERDS in proband
mother.erds.vcf.cluster.txt = merged CNVs detected by ERDS in mother
father.erds.vcf.cluster.txt = merged CNVs detected by ERDS in father
father.calls.txt.cluster.txt = merged CNVs detected by CNVnator in father
mother.calls.txt.cluster.txt = merged CNVs detected by CNVnator in mother 
sorted_refgene_b37_cds_3.bed = bed file of genic region

**Comment by bjtrost** [comment]
Hi,

Sorry for the slow reply. I think I know what the problem is. We *did* actually apply another filter, which is that the CNV had to be rare (less than 1% frequency) in parents from MSSNG (https://www.mss.ng). This greatly reduces the number of CNVs in any given individual. Unfortunately, you will not be able to apply this exact filter, as you will not have access to these frequencies (given that MSSNG is controlled-access). However, we may be able to provide frequencies from 2,504 1000 Genomes Project population controls, as we have ran ERDS and CNVnator on these samples. I will look into whether we can provide this. It might take a few days.

Thanks,

Brett

**Comment by ikeadeshina** [comment]
Hi Brett, 

I appreciate you looking into this for me. A few days is no problem at all. 

Thank you, 
Ike

**Comment by ikeadeshina** [comment]
Hi Brett,

I actually have access to MSSNG and have been able to query the "cnvs" table provided in the mssng_20171020a release. I see the columns with the erds and cnvnator percent frequency in parents. Do you know if this excludes parents that are affected (AFFECTION = 2)?

**Comment by bjtrost** [comment]
That is correct. Affected individuals are not included in the frequencies. FYI, we will be releasing ERDS and CNVnator CNV calls for MSSNG DB6 in the relatively near future (1-2 months).

**Comment by ikeadeshina** [comment]
Great! Thank you for your help.
